// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbkhuifngnmgsoeamlno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJia2h1aWZuZ25tZ3NvZWFtbG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Njg1NDYsImV4cCI6MjA2MzE0NDU0Nn0.7XSTKNCAL3L4gI3I1a3On4A7hIX5cr6tPhBj0HfForw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);